# Generated by Django 4.2.7 on 2025-11-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='palabra_clave',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
