# Generated by Django 4.2.7 on 2025-11-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_palabra_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_juego',
            field=models.CharField(choices=[('jugando', 'Jugando'), ('completado', 'Completado')], default='jugando', max_length=20),
        ),
    ]
